# -*- coding: utf-8 -*-
"""RouteOp

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M6N2UY6KuTgx7v7ZimUpiKL1TvcZFwS7
"""

pip install geopandas requests folium leafmap

"""# **Define Tourist Locations**"""

import geopandas as gpd
import folium
import requests
import leafmap

# Define tourist locations with latitude & longitude
locations = {
    "Eiffel Tower": (48.858844, 2.294351),
    "Louvre Museum": (48.860611, 2.337644),
    "Notre-Dame Cathedral": (48.852968, 2.349902),
    "Champs-Élysées": (48.869798, 2.307647),
    "Sacré-Cœur": (48.886705, 2.343104)
}

# Convert locations to a list of coordinates
waypoints = ";".join([f"{lon},{lat}" for lat, lon in locations.values()])
waypoints

"""# **Request Optimized Route from OSRM**"""

# OSRM API URL (change 'car' to 'foot' or 'bike' if needed)
osrm_url = f"http://router.project-osrm.org/route/v1/car/{waypoints}?overview=full&geometries=geojson"

# Send request to OSRM server
response = requests.get(osrm_url)
route_data = response.json()

# Extract the optimized route
route_geometry = route_data["routes"][0]["geometry"]

"""# **Visualize the Optimized Route on a Map**"""

# Create a folium map centered at Paris
map_center = [48.8566, 2.3522]  # Paris center coordinates
m = folium.Map(location=map_center, zoom_start=13)

# Add route to map
folium.PolyLine(
    locations=[(lat, lon) for lon, lat in route_geometry["coordinates"]],
    color="blue",
    weight=5,
    opacity=0.7
).add_to(m)

# Add markers for each tourist location
for place, (lat, lon) in locations.items():
    folium.Marker(location=[lat, lon], popup=place, icon=folium.Icon(color="red")).add_to(m)

# Display the interactive map
m

